### ISSUE TITLE
[토큰 관련] Axios baseURL 설정 문제

### ISSUE THREAD

**Issue by JuhwanLeeKR** [PBL-magazine/frontend-juhwan#7]
어제부터 골머리 앓고 있던, 로그인 요청을 했을 시 토큰이 브라우저에 들어오지 않는 문제가 발생했었습니다.
하루종일 이것저것 찾아봤지만, 해결이 되지 않았고 원영님 frontend 파일을 다운받아 실행을 해보았습니다.

이때, 정상적으로 실행이 되는 것을 확인하였고 소스를 까보기 시작했습니다.

<img width="498" alt="PBL-magazine_backend-choewy_ Magazine Backend - Chrome 22-04-26 (화) 오전 10_03_44" src="https://user-images.githubusercontent.com/87694150/165198699-bc4267dc-8ba2-4dd5-aca7-e8f39a6170c3.png">

원영님 frontend 파일 `index.js` 부분이 환경변수 처리되어있는데도 불구하고, proxy 설정을 해놓으니 정상적으로 작동하는 것을 확인했습니다.

거기에 힌트를 얻어 제 file `axios.js` 파일에서 baseURL 부분을 주석 처리하니 제대로 토큰이 받아지는 상황이 벌어졌습니다.

## 😡 기존

<img width="565" alt="axios js - frontend-juhwan - Visual Studio Code 22-04-26 (화) 오전 9_59_36" src="https://user-images.githubusercontent.com/87694150/165199393-d72a88d6-ea09-4711-856b-df938843ab31.png">

![토큰 안받아짐](https://user-images.githubusercontent.com/87694150/165199536-d397cad2-1fa8-4f72-aec8-ea415b628e7e.gif)

## ⁉️ baseURL 부분을 주석 처리한 후

<img width="566" alt="axios js - frontend-juhwan - Visual Studio Code 22-04-26 (화) 오전 10_00_47" src="https://user-images.githubusercontent.com/87694150/165199722-43df6104-1a8d-4370-a1d5-1c499a06545f.png">

![토큰 받아짐](https://user-images.githubusercontent.com/87694150/165199556-8757db30-3ed6-4f63-b870-b3fbe87c8d0a.gif)

토큰이 받아와지지만
baseURL 설정을 했을때는 되지 않고, proxy 설정을 한 경우에만 정상적으로 작동이 됩니다.

정상적으로 해결되었다는 생각이 들지 않아
임시로 해결한 방법을 알려드리며

1. proxy 돌리는 방법이 아닌, baseURL 설정을 해도 토큰을 브라우저에 넣을 방법이 없는지?
2. 이게 맞는 방법인지..?

등 다양한 피드백 부탁드립니다.

**Comment by JuhwanLeeKR** [comment]
https://www.youtube.com/watch?v=-2TgkKYmJt4&t=1215s

![(11)  10분 테코톡  🌳 나봄의 CORS - YouTube - Chrome 22-04-26 (화) 오전 10_36_18](https://user-images.githubusercontent.com/87694150/165201573-8b888ae9-f0a9-4474-9fa0-99bc3b4f8e9d.png)

요런식으로 백이랑 프론트에서 처리를 해야되나? 싶기도 합니다

**Comment by choewy** [comment]
간단하게 정리한 내용을 전달드립니다.

------------------------------------------------
일단 다음 내용에 대해서 생각해봐야 합니다.

1.  PUBLIC_URL은 무엇인가?
2. 프록시와 CORS는 무엇인가?
3. baseURL은 무엇인가?

## 1. PUBLIC_URL은 무엇인가?

현재 환경변수의 PUBLIC_URL은 `package.json`의 `"homepage": ""`에 해당하는 루트 경로를 뜻합니다. 이는 웹 사이트의 루트 경로를 다른 곳으로 변경할 때 사용하는 환경변수 입니다.예를 들어, 자신이 배포한 웹 사이트의 루트 경로를 `http://~/`가 아닌 `http://~/app`으로 설정할 때 `package.json`에서 `"homepage": "/app"`를 추가할 수 있습니다. 뿐만 아니라, React로 빌드된 `index.html`은 여러 개의 정적(static) 파일을 `html`로 불러들이는데, 이때 PUBLIC_URL은 정적 파일의 경로를 뜻하기도 합니다. 따라서, 프록시와는 아무런 연관이 없습니다.

## 2. 프록시와 CORS

프록시는 일반적으로 중간에 존재하는 서버를 뜻하기도 하는데, 프론트엔드에서의 프록시의 경우 이와는 조금 다른 개념입니다. 예를 들어, 클라이언트 도메인 A(www.a.com)와 백엔드 서버 B(www.b.com)가 서로 리소스를 주고 받을 때 CORS(Cross-Origin-Resource-Sharing) 이슈가 발생합니다. 이는 A와 B의 출처(origin) 즉, URL이 다른 환경에서 데이터를 주고 받는 것은 결코 안전한 행위가 아니기 때문에 웹 브라우저에서 보안 목적으로 이를 차단하는 정책입니다. 이를 해결할 수 있는 방법으로는 백엔드 CORS 설정, 별도의 Proxy 서버 구축 등의 방법이 있습니다.

## 3. baseURL 설정

프론트엔드에서 프록시를 설정했다는 것은 자신이 다른 곳으로 요청을 보낼 때 웹 브라우저에게 자신의 경로를 요청 받는 쪽(서버)의 경로로 속인다는 의미라고 할 수 있습니다. 예를 들어, 프론트엔드의 URL이 `http://a.com`이라고 가정해봅시다. proxy를 `http://b.com`으로 설정해놓고, axios 요청을 보낼 때 `/api/posts`로 보내면, 요청 경로가 다음과 같은 과정으로 변경됩니다.

- 처음 요청 시(웹 브라우저 속임) : `http://a.com/api/posts`
- 실제 요청 경로: `http://b.com/api/posts`
- 응답 받을 때(웹 브라우저 속임) : `http://a.com/api/posts`
- 실제 응답 경로: `http://b.com/api/posts`

그런데, baseURL을 `http://b.com`으로 설정하면 아예 요청 경로가 `http://b.com`으로 고정되기 때문에 프록시를 적용한 이유가 없게 됩니다. 따라서, baseURL을 현재 루트 경로인 `/`로 설정해주면 해결할 수 있습니다.

**Comment by choewy** [comment]
영상에 나온대로 일단 서버 쪽에서는 아래와 같은 설정이 되어있는 상태입니다.

```
- Access-Control-Allow-Origin : *
- Access-Control-Allow-Headers : *
- Access-Control-Allow-Credentials : true
```

이게... 검색을 해서 정보를 얻는다고 해도 잘못된 내용이 많기도 하고, 한 번에 완벽하게 이해하기 어려운 부분이 있는 것 같습니다. 따라서, 큰 흐름 정도만 파악하고, 이것저것 직접 적용 후 해결해보는게 가장 좋은 방법이 아닐까 생각을 해봅니다.

**Comment by JuhwanLeeKR** [comment]
답변 감사합니다 👍
